version: '3'

services:
  minio:
    image: minio/minio:RELEASE.2023-07-18T17-49-40Z
    restart: always
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=test1234
      #Needs to be stored somewhare safe
      - MINIO_ROOT_PASSWORD=test1234
    volumes:
      - minio_storage:/data
  minio-seeder:
    image: minio/mc
    volumes:
      - ./dataset:/data
    depends_on:
      - minio
    #Sleep command is the simplest way to wait before minIO server gets ready
    #We could do something more sophisticated but it aint worth the effort
    entrypoint: >
      /bin/sh -c "
      sleep 15;
      /usr/bin/mc alias set myminio http://minio:9000 test1234 test1234;
      /usr/bin/mc mb myminio/employee-data;
      /usr/bin/mc cp --recursive /data myminio/employee-data;
      "
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: myuser
      #Needs to be stored somewhare safe
      POSTGRES_PASSWORD: mypasswordt
    volumes:
      - "./init:/docker-entrypoint-initdb.d"
    ports:
      - "5432:5432"

volumes:
  minio_storage: {}